infos:
  contact:
    email: test@test-tacocloud.com
    phone: +32 0XX XX XX XX

server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: webapp-resource
  task:
    execution:
      thread-name-prefix: cmahy-broker-consumer-
      pool:
        core-size: 2
        max-size: 20
        queue-capacity: 10000
  rsocket:
    server:
      port: 9080
      transport: tcp
#      transport: websocket
#      mapping-path: /web-socket/

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics,notes
  endpoint:
    health:
      access: read_only
      show-details: when_authorized
      show-components: when_authorized
    metrics:
      access: read_only
    loggers:
      access: read_only
    info:
      access: read_only
